server:
  port: 8082
  shutdown: graceful
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:production}
  application:
    name: service-two
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
  info:
    env:
      enabled: true
